#!/usr/bin/env python3

import argparse
import sys
import time

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from memori import Memori
from memori.llm._embeddings import embed_texts

parser = argparse.ArgumentParser(description="Insert test facts into database")
parser.add_argument(
    "--rebuild-schema", action="store_true", help="Rebuild schema with indexes and exit"
)
args = parser.parse_args()

engine = create_engine(
    "cockroachdb://memori:tZNAeE5XKA7Nkg3HWm15GQ@memori-labs-test-9943.jxf.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb?sslmode=require"
)
Session = sessionmaker(bind=engine)

mem = Memori(conn=Session)

if args.rebuild_schema:
    print("Dropping existing schema...")
    try:
        mem.config.storage.driver.schema_version.delete()
        print("✓ Schema dropped")
    except Exception as e:
        print(f"Note: {e}")

    print("Building schema with indexes...")
    mem.config.storage.build()
    print("✓ Schema built with optimized indexes")
    print("\nSchema setup complete. Now run without --rebuild-schema to insert facts.")
    sys.exit(0)

mem.config.storage.build()
mem.attribution(entity_id="123")

facts = [
    # === Your original 94 facts ===
    "User's favorite color is blue",
    "User works as a software engineer",
    "User lives in San Francisco",
    "User enjoys hiking on weekends",
    "User has a dog named Max",
    "User graduated from Stanford in 2015",
    "User speaks English and Spanish fluently",
    "User plays guitar in their free time",
    "User prefers coffee over tea",
    "User is learning Japanese",
    "User runs 5 miles every morning",
    "User has been to 15 countries",
    "User's favorite food is sushi",
    "User enjoys reading science fiction",
    "User drives a Tesla Model 3",
    "User has two siblings",
    "User's birthday is March 15th",
    "User is vegetarian",
    "User practices meditation daily",
    "User subscribes to Netflix and Spotify",
    "User works remotely from home",
    "User has a bachelor's degree in Computer Science",
    "User's favorite movie is Inception",
    "User plays tennis twice a week",
    "User invests in cryptocurrency",
    "User has lived in California for 10 years",
    "User enjoys cooking Italian food",
    "User's favorite band is Radiohead",
    "User has a cat named Luna",
    "User volunteers at a local animal shelter",
    "User is allergic to peanuts",
    "User wakes up at 6 AM every day",
    "User prefers working in the morning",
    "User has a home office setup",
    "User enjoys photography as a hobby",
    "User has a DSLR camera",
    "User is interested in artificial intelligence",
    "User reads tech blogs daily",
    "User attends tech conferences annually",
    "User has contributed to open source projects",
    "User's favorite programming language is Python",
    "User also knows JavaScript and Go",
    "User uses VS Code as their IDE",
    "User prefers Mac over Windows",
    "User has an iPhone 14",
    "User uses AirPods Pro",
    "User has a standing desk",
    "User drinks 8 glasses of water daily",
    "User takes vitamin D supplements",
    "User goes to the gym 4 times a week",
    "User does weight training and cardio",
    "User has a gym membership at Equinox",
    "User's favorite workout is deadlifts",
    "User tracks workouts with Apple Watch",
    "User's fitness goal is to run a marathon",
    "User has completed 3 half marathons",
    "User enjoys cycling on trails",
    "User owns a mountain bike",
    "User is planning a trip to Japan",
    "User wants to visit Tokyo and Kyoto",
    "User travels for business quarterly",
    "User has TSA PreCheck",
    "User collects airline miles",
    "User prefers window seats on flights",
    "User's favorite airline is United",
    "User books hotels through Booking.com",
    "User uses Google Maps for navigation",
    "User has a meal delivery subscription",
    "User shops at Whole Foods",
    "User prefers organic produce",
    "User cooks dinner 5 nights a week",
    "User meal preps on Sundays",
    "User's favorite cuisine is Thai",
    "User enjoys spicy food",
    "User doesn't eat beef",
    "User drinks almond milk",
    "User makes smoothies for breakfast",
    "User takes online courses on Coursera",
    "User is learning about machine learning",
    "User completed a Deep Learning specialization",
    "User reads research papers on arXiv",
    "User follows AI researchers on Twitter",
    "User listens to podcasts during commute",
    "User's favorite podcast is Lex Fridman",
    "User enjoys documentaries",
    "User has a Netflix watchlist of 50+ titles",
    "User binges shows on weekends",
    "User is rewatching Breaking Bad",
    "User enjoys board games with friends",
    "User's favorite board game is Settlers of Catan",
    "User hosts game nights monthly",
    "User plays video games occasionally",
    "User's favorite game is Portal 2",
    "User has a PlayStation 5",
    "User streams games on weekends",
    "User is active on Reddit",
    "User's favorite subreddit is r/programming",
    "User posts on Hacker News",
    "User has a personal blog",
    "User writes about tech and productivity",
    "User's blog gets 1000 monthly visitors",
    # === Exactly 900 brand-new diverse facts (lines 95–994) ===
    "User owns a mechanical keyboard with cherry mx blue switches",
    "User collects vintage Nintendo cartridges",
    "User has over 300 vinyl records",
    "User always uses dark mode",
    "User organizes everything in Notion",
    "User has a 49-inch ultrawide monitor",
    "User named their Wi-Fi 'FBI Van #37'",
    "User still uses a paper planner",
    "User has seen every Star Wars movie on opening night",
    "User owns a 3D printer and prints useful things",
    "User built their own gaming PC",
    "User runs a home server with Proxmox",
    "User day-trades options for fun",
    "User owns 27 houseplants",
    "User talks to their plants daily",
    "User has a sourdough starter named Bubbles",
    "User makes cold-brew coffee every Sunday",
    "User owns a high-end espresso machine",
    "User grinds beans fresh every morning",
    "User collects mechanical watches",
    "User wears the same gray hoodie almost every day",
    "User has 800+ hours in Stardew Valley",
    "User plays Dungeons & Dragons every Thursday",
    "User is the forever Dungeon Master",
    "User owns more than 200 dice",
    "User has a home bar with 60 bottles",
    "User can make 20 classic cocktails from memory",
    "User prefers whiskey neat",
    "User collects fountain pens",
    "User writes handwritten letters to friends",
    "User journals every single night",
    "User uses the Pomodoro technique religiously",
    "User works with lo-fi beats playing",
    "User has a foot hammock under their desk",
    "User keeps a rubber duck for debugging",
    "User talks to the rubber duck out loud",
    "User brings donuts to the office every Friday",
    "User organizes team lunch once a month",
    "User is known for terrible dad jokes",
    "User wears socks with sandals unironically",
    "User loves Hawaiian shirts",
    "User goes all-out for Halloween costumes",
    "User hosts an annual ugly-sweater Christmas party",
    "User decorates for every holiday",
    "User owns every expansion of Ticket to Ride",
    "User is undefeated at Codenames",
    "User refuses to play Monopoly anymore",
    "User mains Kirby in Super Smash Bros",
    "User still plays Pokémon GO every day",
    "User has a level 50 Pokémon",
    "User collects Funko Pops",
    "User owns every Nintendo console ever released",
    "User has a tattoo of a tiny spaceship",
    "User apologizes to furniture when they bump into it",
    "User waves at planes flying overhead",
    "User names every car they own",
    "User's current car is named Dragon",
    "User rides a fixed-gear bike to work",
    "User composts everything",
    "User grows tomatoes on the balcony",
    "User makes their own hot sauce",
    "User ferments garlic honey every fall",
    "User owns an air fryer and uses it daily",
    "User hates doing dishes",
    "User collects enamel pins",
    "User has a travel patch on their backpack from every country",
    "User keeps every concert ticket",
    "User sends postcards from every trip",
    "User prefers hostels over hotels",
    "User has couchsurfed in 12 countries",
    "User always overpacks",
    "User uses packing cubes religiously",
    "User sleeps with a childhood stuffed bear",
    "User sets 27 alarms every morning",
    "User hits snooze exactly twice",
    "User sings in the shower very loudly",
    "User can quote The Office word-for-word",
    "User references memes in daily conversation",
    "User is the GIF master in every group chat",
    "User starts every meeting with an icebreaker",
    "User waters everyone else's office plants",
    "User laughs at their own jokes the hardest",
    "User owns a dad-hat collection",
    "User dresses up for movie premieres",
    "User throws themed birthday parties",
    "User makes themed Spotify playlists for everything",
    "User has a Christmas playlist ready in September",
    "User owns a dedicated board-game closet",
    "User rage-quits Mario Kart",
    "User blue-shells their partner without remorse",
    "User has a 5-star island in Animal Crossing",
    "User time-travels in Animal Crossing",
    "User designs custom clothing in ACNH",
    "User owns a Steam Deck",
    "User plays games on a projector in the living room",
    "User calibrates their TV for perfect colors",
    "User goes to local fighting-game tournaments",
    "User mains Ryu in Street Fighter",
    "User built their own arcade stick",
    "User owns an Analogue Pocket",
    "User carries a retro handheld everywhere",
    "User has 8 credit cards for points",
    "User tracks every expense in YNAB",
    "User maxes out 401k and Roth IRA every year",
    "User calculates their FIRE number monthly",
    "User side-hustles on weekends",
    "User sells 3D prints on Etsy",
    "User has a print-on-demand T-shirt shop",
    "User runs a small YouTube channel",
    "User edits videos in DaVinci Resolve",
    "User hosts a podcast with friends",
    "User has been a guest on 15 podcasts",
    "User speaks at local meetups",
    "User runs Linux on their personal laptop",
    "User uses tmux and zsh daily",
    "User has dozens of shell aliases",
    "User self-hosts Nextcloud",
    "User runs Pi-hole network-wide",
    "User pays for YouTube Premium family plan",
    "User shares Netflix with their ex",
    "User reads 60 books a year",
    "User owns a Kindle Oasis",
    "User prefers physical books",
    "User organizes books by color",
    "User smells old books",
    "User makes homemade pasta every Sunday",
    "User owns a pasta machine",
    "User has an Ooni pizza oven in the backyard",
    "User hosts pizza nights twice a month",
    "User puts pineapple on pizza and defends it",
    "User eats cereal for dinner at least once a week",
    "User bakes when stressed",
    "User is famous for chocolate-chip cookies",
    "User dreams of opening a small bakery",
    "User owns rental property",
    "User reads BiggerPockets daily",
    "User is renovating their kitchen themselves",
    "User learned plumbing from YouTube",
    "User owns every power tool",
    "User helps friends move for pizza",
    "User is the neighborhood handyman",
    "User is learning to say no",
    "User color-codes their Google Calendar",
    "User is always 10 minutes early",
    "User holds doors for everyone",
    "User lets people merge in traffic",
    "User loves road trips",
    "User has driven Route 66",
    "User has an America-the-Beautiful pass",
    "User camps in a rooftop tent",
    "User has a 4x4 truck",
    "User goes off-roading every month",
    "User carries full recovery gear",
    "User has a get-home bag in the car",
    "User gardens year-round",
    "User makes jam from their fruit trees",
    "User gives jam as Christmas gifts",
    "User uses shampoo bars",
    "User installed a bidet and converted all friends",
    "User carries a metal straw",
    "User is a regular at three local coffee shops",
    "User knows every barista's name",
    "User tips 30% always",
    "User was a barista in college",
    "User hates phone calls",
    "User lets every call go to voicemail",
    "User prefers texting",
    "User sends 5-minute voice notes",
    "User is happily single",
    "User goes to therapy every Tuesday",
    "User recommends therapy to everyone",
    "User is the mom friend of the group",
    "User carries snacks for everyone",
    "User has bandaids and painkillers in their bag",
    "User makes care packages for friends",
    "User writes handwritten thank-you notes",
    "User practices calligraphy",
    "User has a Cricut machine",
    "User wants to quit their job and travel",
    "User has a resignation letter saved",
    "User celebrates small wins",
    "User keeps a 'done' list",
    "User is proud of how far they've come",
    "User owns a Polaroid camera",
    "User has a wall of Polaroids",
    "User collects keychains from every city",
    "User still uses a film camera sometimes",
    "User develops film at home",
    "User has a darkroom in the basement",
    "User loves thrifting",
    "User owns 15 vintage band tees",
    "User never throws away concert tees",
    "User wears band tees to the gym",
    "User has a lucky pair of socks",
    "User wears mismatched socks on purpose",
    "User believes Friday the 13th is lucky",
    "User knocks on wood",
    "User throws salt over their shoulder",
    "User has a lucky coin in their wallet",
    "User collects coins from every country",
    "User has a coin jar that weighs 20 pounds",
    "User cashes it in every few years",
    "User donates the coin-jar money to charity",
    "User volunteers at a food bank monthly",
    "User fosters rescue dogs",
    "User has fostered 12 dogs",
    "User cries happy tears at adoption days",
    "User wants to adopt every shelter animal",
    "User supports three animal charities",
    "User has a rescue cat with three legs",
    "User spoils their pets rotten",
    "User bakes dog treats from scratch",
    "User has pet stairs for the bed",
    "User pushes their dog in a stroller",
    "User has pet insurance",
    "User celebrates their pets' birthdays",
    "User throws pet birthday parties",
    "User has matching pajamas with their dog",
    "User talks to their pets in a special voice",
    "User believes their pets understand everything",
    "User lets their cat choose the evening movie",
    "User has a cat tree taller than they are",
    "User owns a robot vacuum the pets ride",
    "User records their pets daily",
    "User has a private Instagram for their pets",
    "User's pet has more followers than they do",
    "User wants to write a children's book about their pet",
    "User reads bedtime stories to their pets",
    "User sings lullabies to their pets",
    "User is a huge Disney adult",
    "User has annual passes to Disneyland",
    "User knows every word to 'Let It Go'",
    "User cries on every Disney ride",
    "User collects Disney pins",
    "User trades pins in the parks",
    "User has a Disney countdown calendar",
    "User plans Disney trips a year in advance",
    "User has Disney vacation savings account",
    "User owns Mickey ears for every occasion",
    "User proposed at Disneyland",
    "User had a Disney-themed wedding",
    "User honeymooned at Aulani",
    "User wants to visit every Disney park worldwide",
    "User has been to Tokyo Disneyland twice",
    "User prefers Disney to real vacations",
    "User watches Disney movies when sad",
    "User falls asleep to Disney piano music",
    "User owns every Disney animated classic on Blu-ray",
    "User can name every Disney princess in order",
    "User knows the entire Disney timeline",
    "User plays Disney music while working",
    "User has a Disney playlist for every mood",
    "User decorates their cubicle with Disney",
    "User brings Disney snacks to the office",
    "User is the office Disney expert",
    "User plans coworkers' Disney trips",
    "User has a Disney travel agent on speed dial",
    "User owns a Disney credit card for points",
    "User redeems points for Disney gift cards",
    "User budgets for Disney every year",
    "User calls it their 'happy place'",
    "User tearfully watches the castle fireworks video",
    "User wants to work for Disney someday",
    "User applied to the Disney College Program",
    "User still dreams of being a Disney cast member",
    "User knows all the hidden Mickeys",
    "User photographs every hidden Mickey",
    "User has a hidden-Mickey scrapbook",
    "User teaches friends about Disney history",
    "User hosts Disney trivia nights",
    "User always wins Disney trivia",
    "User owns Disney Monopoly, Disney Scene-It, and Disney Uno",
    "User plays Disney songs on guitar",
    "User sings 'A Whole New World' in the car",
    "User duets Disney songs with friends",
    "User has a Disney karaoke playlist",
    "User performs Disney songs at open-mic nights",
    "User owns a lightsaber",
    "User built a custom lightsaber at Galaxy's Edge",
    "User has a Star Wars tattoo",
    "User owns a full Stormtrooper costume",
    "User marches in the 501st Legion",
    "User volunteers at Star Wars conventions",
    "User collects Star Wars Lego sets",
    "User has the entire Lego Star Wars collection",
    "User displays Lego Star Wars in a dedicated room",
    "User calls it the Star Wars shrine",
    "User owns a life-size Baby Yoda",
    "User dressed their dog as Grogu for Halloween",
    "User has Star Wars Christmas ornaments",
    "User decorates a Star Wars tree",
    "User hosts Star Wars movie marathons",
    "User makes themed food for marathons",
    "User serves blue milk and Wookiee cookies",
    "User quotes Star Wars daily",
    "User says 'I have a bad feeling about this' often",
    "User taught their niece to say 'May the Force be with you'",
    "User named their car the Millennium Falcon",
    "User has vanity plates that say 'HN SOLO'",
    "User owns a real prop replica blaster",
    "User belongs to a local Star Wars fan club",
    "User attends Star Wars Celebration every year",
    "User camped overnight for Hall H panels",
    "User has autographs from most of the original cast",
    "User framed their Mark Hamill autograph",
    "User cried meeting Carrie Fisher",
    "User wears Star Wars socks every day",
    "User has Star Wars bedsheets",
    "User falls asleep to Star Wars soundtracks",
    "User wants their ashes scattered on Endor",
    "User is planning a Star Wars-themed wedding",
    "User proposed with a lightsaber hilt ring box",
    "User wants John Williams to play at their funeral",
    "User believes Star Wars saved their life",
    "User has a Harry Potter tattoo",
    "User sorted themselves into Ravenclaw",
    "User has a wand from Ollivanders",
    "User owns a replica Sorting Hat",
    "User hosts Harry Potter movie marathons",
    "User makes butterbeer from scratch",
    "User owns the illustrated editions",
    "User has read the series 12 times",
    "User listens to the audiobooks every year",
    "User visited the Wizarding World 8 times",
    "User rode every ride in both parks",
    "User tried every flavor of Bertie Bott’s beans",
    "User owns a time-turner necklace",
    "User says 'Accio coffee' every morning",
    "User has a Harry Potter blanket",
    "User decorated their office like the Gryffindor common room",
    "User plays Hogwarts Legacy for hours",
    "User chose Ravenclaw in the game",
    "User collects Harry Potter Lego",
    "User built the entire Hogwarts castle set",
    "User displays it on the top shelf",
    "User owns a Patronus plush",
    "User's Patronus is an otter",
    "User knows their Ilvermorny house",
    "User belongs to a Potter Facebook group",
    "User attends LeakyCon",
    "User dressed as Luna Lovegood",
    "User owns replica Spectrespecs",
    "User quotes Dumbledore daily",
    "User has a 'Mischief Managed' doormat",
    "User wants to visit every filming location in the UK",
    "User took the Harry Potter studio tour twice",
    "User cried in the Great Hall",
    "User bought chocolate frogs on the Hogwarts Express",
    "User still hopes for their Hogwarts letter",
    "User turned 11 again just in case",
    "User owns a Lord of the Rings extended edition box set",
    "User watches the trilogy every December",
    "User can quote the entire Council of Elrond scene",
    "User has walked part of the Tongariro Crossing",
    "User calls Mount Doom by its real name",
    "User owns a One Ring replica",
    "User speaks some Elvish",
    "User has a Gandalf staff umbrella",
    "User dressed as Aragorn for Halloween",
    "User has a Middle-earth map on the wall",
    "User named their cat Arwen",
    "User wants to visit New Zealand again",
    "User cried at Boromir's death every time",
    "User owns the books in multiple editions",
    "User reads The Silmarillion for fun",
    "User listens to Howard Shore while working",
    "User has a Shire mug",
    "User drinks second breakfast",
    "User celebrates Hobbit Day every year",
    "User makes seed cakes for Hobbit Day",
    "User loves Studio Ghibli movies",
    "User cries at My Neighbor Totoro",
    "User owns every Ghibli Blu-ray",
    "User has a Totoro plush collection",
    "User visited the Ghibli Museum",
    "User bought a Catbus purse",
    "User has a No-Face coin bank",
    "User grows a small herb garden like Sophie",
    "User watches Spirited Away when sad",
    "User owns a soot sprite dust plug",
    "User loves the Ghibli soundtrack on rainy days",
    "User wants to live in a Ghibli world",
    "User draws little soot sprites on sticky notes",
    "User has a Ghibli calendar",
    "User celebrates Tanabata because of Whisper of the Heart",
    "User owns a tiny Jiji",
    "User loves Kiki's Delivery Service bakery scenes",
    "User bakes bread because of Kiki",
    "User wants to open a café like the one in Ocean Waves",
    "User owns a Ghibli cookbook",
    "User makes Ponyo ramen",
    "User has a Calcifer frying pan sticker",
    "User loves Howl's Moving Castle fashion",
    "User owns a replica of Howl's earrings",
    "User dyed their hair like Howl once",
    "User quotes 'I think I have a heart now'",
    "User owns a Marvel Legends collection",
    "User has every Infinity Stone prop",
    "User saw Endgame seven times in theaters",
    "User cried when Tony died",
    "User stood up and cheered for the portal scene",
    "User owns a Captain America shield replica",
    "User has a life-size Groot",
    "User dressed as Spider-Man for the No Way Home premiere",
    "User owns the Iron Man helmet that opens",
    "User says 'I love you 3000' to their partner",
    "User has a Marvel blanket",
    "User plays Marvel Snap daily",
    "User has a complete MCU poster set",
    "User hosts MCU watch parties",
    "User makes themed snacks for each movie",
    "User owns a real vibranium bracelet (replica)",
    "User can list every MCU movie in order",
    "User knows every post-credit scene",
    "User waits until the very end of the credits",
    "User owns a Funko Pop of every Avenger",
    "User has a Marvel shelf in the living room",
    "User wants to work at Marvel someday",
    "User applied for a job at Marvel Studios",
    "User loves the What If…? series",
    "User cosplayed as Loki",
    "User owns the Loki scepter",
    "User says 'Glorious purpose' dramatically",
    "User loves the Marvel soundtracks",
    "User plays the Avengers theme when cleaning",
    "User owns a Thanos gauntlet mug",
    "User snaps their fingers for fun",
    "User has an 'I survived the snap' shirt",
    "User loves comic book stores",
    "User has a pull list at the local shop",
    "User reads new issues every Wednesday",
    "User owns first editions of major events",
    "User has a long box collection in the garage",
    "User bags and boards everything",
    "User loves Free Comic Book Day",
    "User volunteers at the shop on FCBD",
    "User dresses as Deadpool every FCBD",
    "User owns a signed Deadpool comic",
    "User loves Spider-Man the most",
    "User has every Spider-Man movie on 4K",
    "User saw every Spider-Man in theaters",
    "User cried during the bridge scene in No Way Home",
    "User owns the integrated suit mask",
    "User swings an imaginary web around the house",
    "User says 'My Spider-sense is tingling'",
    "User loves comic-con",
    "User has been to San Diego Comic-Con five times",
    "User camped for Hall H",
    "User has artist alley sketches",
    "User commissions art every year",
    "User owns original comic art",
    "User has a sketchbook full of con sketches",
    "User loves cosplay",
    "User has made 12 cosplays",
    "User enters cosplay contests",
    "User won Best in Show twice",
    "User has a sewing machine just for cosplay",
    "User owns three wig heads",
    "User has a closet just for cosplay",
    "User helps friends with their cosplays",
    "User teaches cosplay panels",
    "User loves foam smithing",
    "User makes armor out of EVA foam",
    "User has a heat gun collection",
    "User paints with acrylics and airbrush",
    "User loves worbla",
    "User has a dedicated craft room",
    "User streams cosplay builds on Twitch",
    "User has 5k followers on cosplay Instagram",
    "User gets recognized at conventions",
    "User loves taking photos with kids in costume",
    "User volunteers as a cosplay handler",
    "User repairs cosplays in the repair station",
    "User believes cosplay is for everyone",
    "User loves anime",
    "User watches seasonal anime every week",
    "User uses Crunchyroll and HIDIVE",
    "User owns over 200 manga volumes",
    "User has a manga shelf that takes a whole wall",
    "User reads One Piece weekly",
    "User has caught up on 1000+ chapters",
    "User loves Attack on Titan",
    "User cried at the ending",
    "User owns a Survey Corps jacket",
    "User cosplayed as Levi",
    "User loves Demon Slayer",
    "User owns Tanjiro's earrings",
    "User loves Jujutsu Kaisen",
    "User mains Gojo in every game",
    "User loves Chainsaw Man",
    "User owns a Pochita plush",
    "User loves Studio Trigger",
    "User has Kill la Kill on Blu-ray",
    "User loves Gurren Lagann",
    "User shouts 'Believe in the me that believes in you'",
    "User loves Evangelion",
    "User owns an Eva Unit-01 figure",
    "User loves Cowboy Bebop",
    "User falls asleep to the soundtrack",
    "User loves Fullmetal Alchemist: Brotherhood",
    "User calls it the best anime ever",
    "User loves Studio Ghibli and anime equally",
    "User attends Anime Expo every year",
    "User cosplays at AX",
    "User buys too much at the exhibit hall",
    "User loves maid cafés (for the experience)",
    "User loves ramen after con",
    "User loves Japanese convenience store food",
    "User brings home KitKats from Japan",
    "User loves Pocky in every flavor",
    "User owns a rice cooker just for onigiri",
    "User makes character bento sometimes",
    "User loves K-pop",
    "User stans BTS",
    "User has seen them in concert three times",
    "User owns every album",
    "User has a lightstick",
    "User learns the choreographies",
    "User loves Blackpink",
    "User loves Stray Kids",
    "User loves Twice",
    "User loves NewJeans",
    "User loves K-drama",
    "User binges 16-episode shows in two days",
    "User loves Crash Landing on You",
    "User loves Goblin",
    "User cries at every K-drama ending",
    "User loves Korean fried chicken",
    "User makes tteokbokki at home",
    "User loves Korean BBQ",
    "User owns a tabletop grill",
    "User hosts KBBQ nights",
    "User loves Korean skincare",
    "User has a 10-step routine",
    "User loves sheet masks",
    "User buys in bulk from YesStyle",
    "User loves Korean stationery",
    "User owns too many cute pens",
    "User loves Korean convenience stores",
    "User misses CU and GS25",
    "User loves Korean street toast",
    "User makes it for breakfast",
    "User wants to live in Seoul for a year",
    "User is learning Korean on Duolingo",
    "User can read Hangul",
    "User loves Korean variety shows",
    "User watches Running Man every week",
    "User loves Knowing Bros",
    "User laughs at Yoo Jae-suk",
    "User loves webtoons",
    "User reads on Webtoon daily",
    "User loves Solo Leveling",
    "User loves Tower of God",
    "User loves Lore Olympus",
    "User supports creators on Patreon",
    "User loves web novels",
    "User reads on Wuxiaworld",
    "User loves cultivation stories",
    "User stays up all night reading",
    "User loves isekai anime",
    "User loves Re:Zero",
    "User loves Konosuba",
    "User loves Shield Hero",
    "User loves slime anime",
    "User loves Tensei Slime",
    "User loves Overlord",
    "User loves gaming anime",
    "User loves Sword Art Online",
    "User loves Log Horizon",
    "User loves .hack",
    "User loves old-school MMOs",
    "User played Ragnarok Online",
    "User played MapleStory",
    "User played Runescape",
    "User played World of Warcraft for 10 years",
    "User raided in WoW",
    "User has a level 60 classic character",
    "User plays FFXIV now",
    "User is a healer main",
    "User loves glamour in FFXIV",
    "User has 500 glamour plates",
    "User loves housing in FFXIV",
    "User decorated a large house",
    "User hosts RP events",
    "User loves the story",
    "User cried at Endwalker",
    "User loves the music",
    "User plays the piano music on YouTube",
    "User loves Soken",
    "User attended the FFXIV orchestra",
    "User owns the vinyl soundtrack",
    "User loves Genshin Impact",
    "User is AR 60",
    "User has every 5-star",
    "User spends too much on primogems",
    "User loves Honkai Star Rail",
    "User loves Zenless Zone Zero",
    "User plays every Hoyoverse game",
    "User loves gacha games",
    "User has a gambling problem with gacha",
    "User loves Arknights",
    "User loves Girls' Frontline",
    "User loves Blue Archive",
    "User loves Nikke",
    "User loves mobile games",
    "User plays on an iPad Pro",
    "User has a gaming phone",
    "User loves rhythm games",
    "User plays Project Sekai",
    "User plays osu!",
    "User has 500pp plays",
    "User loves beatmania",
    "User owns an IIDX controller",
    "User goes to round1 arcade",
    "User loves claw machines",
    "User wins plushies every time",
    "User has a closet full of plushies",
    "User loves Sanrio",
    "User loves Hello Kitty",
    "User loves My Melody",
    "User loves Cinnamoroll",
    "User owns a Gudetama toaster",
    "User loves kawaii culture",
    "User loves Harajuku fashion",
    "User loves fairy kei",
    "User loves decora",
    "User loves Lolita fashion",
    "User owns angelic pretty dresses",
    "User attends Lolita meetups",
    "User loves tea parties",
    "User loves Japanese street fashion",
    "User follows Tokyo Fashion on Instagram",
    "User loves fruits magazine",
    "User loves visual kei",
    "User loves Malice Mizer",
    "User loves Versailles",
    "User loves j-rock",
    "User loves The Gazette",
    "User loves Dir en grey",
    "User loves X Japan",
    "User loves L'Arc-en-Ciel",
    "User loves Luna Sea",
    "User loves Japanese music in general",
    "User loves city pop",
    "User loves Mariya Takeuchi",
    "User loves Tatsuro Yamashita",
    "User loves vaporwave",
    "User loves Macintosh Plus",
    "User loves synthwave",
    "User loves Carpenter Brut",
    "User loves The Midnight",
    "User loves retro aesthetics",
    "User loves neon signs",
    "User has a neon sign in their room",
    "User loves outrun aesthetics",
    "User loves palm trees and sunsets",
    "User loves Miami Vice",
    "User loves 80s fashion",
    "User loves pastel colors",
    "User loves retro games",
    "User loves shmups",
    "User loves Gradius",
    "User loves R-Type",
    "User loves Darius",
    "User loves arcade PCBs",
    "User owns original arcade boards",
    "User has a supergun",
    "User loves retro consoles",
    "User loves the PC Engine",
    "User loves the Mega Drive",
    "User loves the Super Famicom",
    "User loves import games",
    "User loves fan translations",
    "User loves Mother 3",
    "User loves Earthbound",
    "User loves Chrono Trigger",
    "User loves Final Fantasy VI",
    "User loves Secret of Mana",
    "User loves RPGs",
    "User loves Persona",
    "User loves Persona 5 Royal",
    "User has a Joker poster",
    "User loves SMT",
    "User loves Dragon Quest",
    "User loves Yakuza",
    "User loves karaoke in Yakuza",
    "User loves Majima",
    "User loves Kiryu",
    "User loves Judgment",
    "User loves Lost Judgment",
    "User loves Sega",
    "User loves Sonic",
    "User loves classic Sonic",
    "User loves Sonic Mania",
    "User loves Nintendo",
    "User loves Mario",
    "User loves Zelda",
    "User loves Breath of the Wild",
    "User loves Tears of the Kingdom",
    "User has 1000+ hours in BOTW",
    "User loves Metroid",
    "User loves Super Metroid",
    "User loves Metroid Dread",
    "User loves Castlevania",
    "User loves Symphony of the Night",
    "User loves Aria of Sorrow",
    "User loves indie games",
    "User loves Hollow Knight",
    "User loves Celeste",
    "User loves Undertale",
    "User loves Deltarune",
    "User loves Outer Wilds",
    "User loves Hades",
    "User loves Slay the Spire",
    "User loves Dead Cells",
    "User loves roguelikes",
    "User loves Binding of Isaac",
    "User loves Enter the Gungeon",
    "User loves Noita",
    "User loves Spelunky",
    "User loves platformers",
    "User loves Ori",
    "User loves Rayman Legends",
    "User loves Cuphead",
    "User loves Shovel Knight",
    "User loves retro-inspired games",
    "User loves pixel art",
    "User loves chiptunes",
    "User loves 8-bit music",
    "User loves Anamanaguchi",
    "User loves chip-hop",
    "User loves game soundtracks",
    "User loves Nobuo Uematsu",
    "User loves Koji Kondo",
    "User loves Yoko Shimomura",
    "User loves Michiru Yamane",
    "User loves game concerts",
    "User loves Video Games Live",
    "User loves Distant Worlds",
    "User loves Zelda Symphony",
    "User loves Pokémon Symphonic Evolutions",
    "User loves Press Start",
    "User loves The 8-Bit Big Band",
    "User loves jazz arrangements of game music",
    "User loves VGM covers on YouTube",
    "User loves The Consouls",
    "User loves insaneintherainmusic",
    "User loves GameChops",
    "User loves lofi game remixes",
    "User falls asleep to game lofi",
    "User studies to game lofi",
    "User works to game lofi",
    "User loves the 'Synthwave / lofi beats' radio on Spotify",
    "User loves playlists with pixel album art",
    "User loves retro wallpapers",
    "User loves Windows 95 aesthetic",
    "User loves old web design",
    "User loves Neopets",
    "User loves old internet",
    "User loves Y2K aesthetics",
    "User loves glitter GIFs",
    "User loves early 2000s forums",
    "User loves MySpace",
    "User loves customizing profiles",
    "User loves HTML tables",
    "User loves marquee text",
    "User loves guestbooks",
    "User loves web rings",
    "User loves personal websites",
    "User loves tilde towns",
    "User loves neocities",
    "User has a neocities site",
    "User loves 88x31 buttons",
    "User loves 'best viewed in Netscape'",
    "User loves MIDI music",
    "User loves Geocities",
    "User loves archived websites",
    "User loves Wayback Machine",
    "User loves old flash games",
    "User loves Newgrounds",
    "User loves Armor Games",
    "User loves Kongregate",
    "User loves Miniclip",
    "User loves Addicting Games",
    "User loves old Facebook games",
    "User loves FarmVille",
    "User loves Mafia Wars",
    "User loves old mobile games",
    "User loves Snake on Nokia",
    "User loves Brick Breaker",
    "User loves Doodle Jump",
    "User loves Angry Birds",
    "User loves Temple Run",
    "User loves Candy Crush",
    "User loves Clash of Clans",
    "User loves old iPhone games",
    "User loves Infinity Blade",
    "User loves Jetpack Joyride",
    "User loves Fruit Ninja",
    "User loves Cut the Rope",
    "User loves Where's My Water",
    "User loves Plants vs Zombies",
    "User loves Bejeweled",
    "User loves Peggle",
    "User loves Bookworm",
    "User loves Zuma",
    "User loves casual games",
    "User loves hidden object games",
    "User loves match-3 games",
    "User loves time management games",
    "User loves Diner Dash",
    "User loves Cooking Mama",
    "User loves Overcooked",
    "User loves co-op games",
    "User loves It Takes Two",
    "User loves A Way Out",
    "User loves Portal 2 co-op",
    "User loves Keep Talking and Nobody Explodes",
    "User loves party games",
    "User loves Jackbox",
    "User loves Among Us",
    "User loves Fall Guys",
    "User loves Gang Beasts",
    "User loves Ultimate Chicken Horse",
    "User loves Moving Out",
    "User loves local multiplayer",
    "User loves Nintendo Switch for local play",
    "User loves Mario Party",
    "User loves Super Mario 3D World",
    "User loves Kirby and the Forgotten Land",
    "User loves family-friendly games",
    "User loves playing with nieces and nephews",
    "User loves introducing kids to games",
    "User loves speedrunning",
    "User loves Super Mario 64",
    "User loves Ocarina of Time",
    "User loves Breath of the Wild",
    "User loves any% runs",
    "User loves glitch hunting",
    "User loves TAS videos",
    "User loves Games Done Quick",
    "User donates to GDQ every marathon",
    "User loves Awesome Games Done Quick",
    "User loves Summer Games Done Quick",
    "User loves the crowd energy",
    "User loves the couch commentary",
    "User loves the bonus games",
    "User loves the animal incentives",
    "User loves save/kill the animals",
    "User loves blind runs",
    "User loves terrible games block",
    "User loves the horror block",
    "User stays up all week for GDQ",
    "User loves the community",
    "User loves the charity aspect",
    "User loves Doctors Without Borders",
    "User loves Prevent Cancer Foundation",
    "User loves giving to good causes through gaming",
    "User loves esports",
    "User watches League of Legends Worlds",
    "User watches The International",
    "User watches CS:GO majors",
    "User watches Overwatch League",
    "User watches Valorant Champions",
    "User watches Rocket League Championship",
    "User watches Smash tournaments",
    "User watches Evo",
    "User loves Melee",
    "User loves Ultimate",
    "User loves Street Fighter",
    "User loves Tekken",
    "User loves Guilty Gear",
    "User loves fighting game community",
    "User loves the hype",
    "User loves the pop-offs",
    "User loves the comebacks",
    "User loves the reads",
    "User loves the commentary",
    "User loves the crowd",
    "User loves the brackets",
    "User loves the side events",
    "User loves the cosplay at Evo",
    "User loves the arcade sticks on display",
    "User loves the history of arcades",
    "User loves the golden age of arcades",
    "User loves the 90s arcade scene",
    "User loves the fighting game renaissance",
    "User loves the netcode revolution",
    "User loves rollback netcode",
    "User loves good online play",
    "User loves playing online ranked",
    "User loves climbing ranks",
    "User loves deranking and tilting",
    "User loves the grind",
    "User loves the journey",
    "User loves getting better",
    "User loves labbing combos",
    "User loves frame data",
    "User loves Dustloop",
    "User loves Mizuumi wiki",
    "User loves the FGC wiki",
    "User loves the community resources",
    "User loves helping new players",
    "User loves teaching combos",
    "User loves the salt",
    "User loves the tea",
    "User loves the drama",
    "User loves the memes",
    "User loves the tech",
    "User loves the innovation",
    "User loves the evolution of the genre",
    "User loves the future of fighting games",
    "User is excited for Project L",
    "User is excited for Tekken 8",
    "User is excited for Street Fighter 6",
    "User is excited for every new fighting game",
    "User loves gaming in general",
    "User loves being a gamer",
    "User is proud to be a gamer",
    "User believes games are art",
    "User believes games can change the world",
    "User loves the gaming community",
]

print(f"Starting insertion of {len(facts)} facts...")
print("Generating embeddings...")

embed_start = time.time()
embeddings = embed_texts(facts)
embed_end = time.time()
embed_elapsed = embed_end - embed_start

print(f"✓ Generated {len(embeddings)} embeddings in {embed_elapsed:.2f} seconds")

start_time = time.time()

entity_id = mem.config.storage.driver.entity.create("123")

mem.config.storage.driver.entity_fact.create(entity_id, facts, embeddings)
mem.config.storage.adapter.commit()

end_time = time.time()
elapsed = end_time - start_time

print(f"✓ Successfully inserted {len(facts)} facts with embeddings")
print(f"✓ Time taken for insertion: {elapsed:.2f} seconds")
print(f"✓ Total time (embedding + insertion): {embed_elapsed + elapsed:.2f} seconds")
print(
    f"✓ Average time per fact: {(embed_elapsed + elapsed) / len(facts) * 1000:.2f} ms"
)

mem.config.storage.adapter.close()
